### ISSUE TITLE
STATA commands used for analytics in this project

### ISSUE THREAD

**Issue by datadig2017** [warwickpsych/NationalValenceIndex#1]
Hi Dr. Sgroi et al,

I came across this publication recently and am interested in the methodology. Particularly, I would like to apply the same algorithm to calculate institutional valence based on internal policy papers. The Nature publication page directed me here for codes but I realized you only published codes for graphics and table outputs. Could you share the algorithm behind the calculations? Manuscript full text is unfortunately behind pay-wall by the journal. Thanks!

Xiaodong Cai

Policy Specialist
Effectiveness Group, Bureau of Policy and Programme Support
United Nations Development Programme
304 East 45th Street, FF-1661, New York, NY 10017
xiaodong.cai@undp.org 
Office: +1.212.906.6283
Skype ID: stata8

**Comment by illushka** [comment]
Hi Xiaodong Cai,

I am planning to create a package to show how we used the Google Books Data to create the valence index at some point.

In the meantime though, as you are keen to understand the method, in a nutshell, for English, we use the “Affective Norms for English Words” (ANEW), a database of nearly 14 thousand English words, all rated on a 1 to 9 valence scale. Here is where we get data of word occurrences over time: http://storage.googleapis.com/books/ngrams/books/datasetsv2.html

We then calculate the National Valence Index by:

1. Take each word from ANEW and figure out the proportion of the word per year (amount of times word occurred divided by total words for the year)
2. Multiply the proportion by the ANEW valence
3. Take the sum of all the products of step 2 for each year to see how valence changes over time

Hope this is clear. 
Best wishes,
Chanuki

**Comment by datadig2017** [comment]
This is very clear and helpful. Thank you @illushka  I will keep an eye open for your future package as well. Best regards.

**Comment by illushka** [comment]
I have now made the code public on https://github.com/alan-turing-institute/ngramsNVI/ and it will soon be copied to this repository. I hope this helps!
Chanuki

**Comment by illushka** [comment]
This now been copied here: https://github.com/warwickpsych/ngramsNVI If you find any issues with the code, do let us know as we have just released it. Thank you
